# Generated by Django 3.2.8 on 2021-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuanLyPhim',
            fields=[
                ('maPhim', models.IntegerField(primary_key=True, serialize=False)),
                ('tenPhim', models.CharField(max_length=50)),
                ('biDanh', models.CharField(max_length=50)),
                ('trailer', models.TextField()),
                ('hinhAnh', models.ImageField(upload_to='')),
                ('moTa', models.TextField()),
                ('ngayKhoiChieu', models.DateTimeField()),
                ('danhGia', models.IntegerField()),
            ],
        ),
    ]
