# Generated by Django 3.2.8 on 2021-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanlyphim',
            name='maNhom',
            field=models.TextField(default='GP01'),
        ),
    ]
