# Generated by Django 3.2.8 on 2021-10-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_quanlyphim_manhom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quanlyphim',
            name='hinhAnh',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='quanlyphim',
            name='maNhom',
            field=models.TextField(),
        ),
    ]
