# Generated by Django 3.2.9 on 2021-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211023_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuanLyHeThongRap',
            fields=[
                ('maHeThongRap', models.IntegerField(primary_key=True, serialize=False)),
                ('tenHeThongRap', models.CharField(max_length=50)),
                ('biDanh', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='images')),
            ],
        ),
    ]
