# Generated by Django 3.2.9 on 2021-11-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_quanlyhethongrap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuanLyHeThongRap',
            new_name='LayThongTinHeThongRap',
        ),
    ]
