# Generated by Django 3.2.9 on 2021-11-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_laythongtinhethongrap_mahethongrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rap',
            fields=[
                ('maRap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenRap', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LayThongTinCumRap',
            fields=[
                ('maCumRap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenCumRap', models.CharField(max_length=50)),
                ('diaChi', models.CharField(max_length=50)),
                ('danhSachRap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.rap')),
            ],
        ),
    ]
