# Generated by Django 3.2.9 on 2021-11-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_laythongtincumrap_rap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laythongtincumrap',
            name='danhSachRap',
        ),
        migrations.AddField(
            model_name='laythongtincumrap',
            name='danhSachRap',
            field=models.ManyToManyField(to='movie.Rap'),
        ),
    ]
