# Generated by Django 3.2.9 on 2021-11-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20211108_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hethongrapchieu',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='hethongrapchieu',
            name='tenHeThongRap',
        ),
        migrations.RemoveField(
            model_name='laybuoichieuphim',
            name='tenRap',
        ),
        migrations.RemoveField(
            model_name='laycumrapchieu',
            name='hinhanh',
        ),
        migrations.RemoveField(
            model_name='laycumrapchieu',
            name='tenCumRap',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='biDanh',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='danhGia',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='hinhAnh',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='maNhom',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='moTa',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='ngayKhoiChieu',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='tenPhim',
        ),
        migrations.RemoveField(
            model_name='laythongtinlichchieuphim',
            name='trailer',
        ),
        migrations.AddField(
            model_name='hethongrapchieu',
            name='id',
            field=models.BigAutoField(auto_created=True, default='Dang Cap Nhat', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laycumrapchieu',
            name='id',
            field=models.BigAutoField(auto_created=True, default='Dang Cap Nhat', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hethongrapchieu',
            name='maHeThongRap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.laythongtinhethongrap'),
        ),
        migrations.AlterField(
            model_name='laycumrapchieu',
            name='maCumRap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.laythongtincumrap'),
        ),
    ]
